language: python
sudo: false

python:
  - 2.6
  - 2.7
  - 3.4
  - 3.5
  - pypy

install:
  - pip install --upgrade pip
  - pip install -e .
  - pip install codecov pytest

script: coverage run --source=dynamallow setup.py test

after_success:
  - codecov
